---
- name: CyberRange
  hosts: localhost
  
  tasks:
  - name: Create a new instance and attaches to a network and passes metadata to the instance
    os_server:
       state: present
       name: cirrosvm01
       image: "cirros-0.6.2-x86_64-disk"
       key_name: os_key
       timeout: 200
       flavor: 100
       auto_ip: no
       network: 3e08d07e-b1ec-48b5-845a-ab27131182ff
       security_groups: default
       auth:
         auth_url: "{{ lookup('env', 'OPENSTACK_AUTH_URL') }}"
         username: "{{ lookup('env', 'OPENSTACK_USERNAME') }}"
         password: "{{ lookup('env', 'OPENSTACK_PASSWORD') }}"
         project_name: demo
         domain_name: "{{ lookup('env', 'OPENSTACK_DOMAIN') }}"
       
       meta:
         os: windows
   
  - name: Create floating ip
    os_floating_ip:
       state: present
       network: public
       server: cirrosvm01 
       auth:
         auth_url: "{{ lookup('env', 'OPENSTACK_AUTH_URL') }}"
         username: "{{ lookup('env', 'OPENSTACK_USERNAME') }}"
         password: "{{ lookup('env', 'OPENSTACK_PASSWORD') }}"
         project_name: demo
         domain_name: "{{ lookup('env', 'OPENSTACK_DOMAIN') }}"

    register: floating_ip_info

  - name: Set fact for floating IPs
    set_fact:
       floating_ips: "{{ floating_ip_info.floating_ip.floating_ip_address }}"

  - name: Output floating ip
    debug:
       var: floating_ips

