---
- name: CyberRange
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create floating ip
      os_floating_ip:
         state: present
         pool: public
         network: public
         server: 
         auth:
           auth_url: "{{ lookup('env', 'OPENSTACK_AUTH_URL') }}"
           username: "{{ lookup('env', 'OPENSTACK_USERNAME') }}"
           password: "{{ lookup('env', 'OPENSTACK_PASSWORD') }}"
           project_name: "{{ lookup('env', 'OPENSTACK_PROJECT') }}"
           domain_name: "{{ lookup('env', 'OPENSTACK_DOMAIN') }}"
           validate_cert: no

      register: floating_ip_info

    - debug:
         var: floating_ip_info

