---
- name: CyberRange
  hosts: localhost
  
  tasks:
  - name: Create a new instance and attaches to a network and passes metadata to the instance
    os_server:
       state: present
       name: crvmwin01
       image: "win2k16img"
       key_name: os_key
       timeout: 200
       flavor: 3
       auto_ip: no
       network: 57325c59-2d2e-47f7-9d19-3d33771e2fee
       security_groups: default
       meta:
         os: windows

  - name: Create a new instance and attaches to a network and passes metadata to the instance
    os_server:
       state: present
       name: crvmwin02
       image: "win2k16img"
       key_name: os_key
       timeout: 200
       flavor: 3
       auto_ip: no
       network: 57325c59-2d2e-47f7-9d19-3d33771e2fee
       security_groups: default
       meta:
         os: windows
   
  - name: Create floating ip
    os_floating_ip:
       state: present
       network: public
       server: crvmwin01 
       auth:
         auth_url: "{{ lookup('env', 'OPENSTACK_AUTH_URL') }}"
         username: "{{ lookup('env', 'OPENSTACK_USERNAME') }}"
         password: "{{ lookup('env', 'OPENSTACK_PASSWORD') }}"
         project_name: "{{ lookup('env', 'OPENSTACK_PROJECT') }}"
         domain_name: "{{ lookup('env', 'OPENSTACK_DOMAIN') }}"

    register: floating_ip_info

  - name: Set fact for floating IPs
    set_fact:
       floating_ips: "{{ floating_ip_info.floating_ip.floating_ip_address }}"

  - name: Output floating ip
    debug:
       var: floating_ips

  - name: Create floating ip
    os_floating_ip:
       state: present
       network: public
       server: crvmwin02 
       auth:
         auth_url: "{{ lookup('env', 'OPENSTACK_AUTH_URL') }}"
         username: "{{ lookup('env', 'OPENSTACK_USERNAME') }}"
         password: "{{ lookup('env', 'OPENSTACK_PASSWORD') }}"
         project_name: "{{ lookup('env', 'OPENSTACK_PROJECT') }}"
         domain_name: "{{ lookup('env', 'OPENSTACK_DOMAIN') }}"

    register: floating_ip_info

  - name: Set fact for floating IPs
    set_fact:
       floating_ips: "{{ floating_ip_info.floating_ip.floating_ip_address }}"

  - name: Output floating ip
    debug:
       var: floating_ips
