--- 
- name: CyberRange
  hosts: localhost  
  
  tasks:
  - name: Create a new instance and attaches to a network and passes metadata to the instance
    os_server:
       state: present
       name: crvmwinad02
       image: "win2k22adimg"
       key_name: os_key
       timeout: 200
       flavor: 101
       auto_ip: no
       network: 57325c59-2d2e-47f7-9d19-3d33771e2fee
       security_groups: default
       auth:
         auth_url: "{{ lookup('env', 'OPENSTACK_AUTH_URL') }}"
         username: "{{ lookup('env', 'OPENSTACK_USERNAME') }}"
         password: "{{ lookup('env', 'OPENSTACK_PASSWORD') }}"
         project_name: "{{ lookup('env', 'OPENSTACK_PROJECT') }}"
         domain_name: "{{ lookup('env', 'OPENSTACK_DOMAIN') }}"
       meta:
         os: windows        
    async: 600
    poll: 5
    register: vm_ad01_created

  - name: Debug inventory - vm_ad01_created 
    debug:
      var: vm_ad01_created
      
  - name: Create floating ip - AD01
    os_floating_ip:
       state: present
       network: public 
       server: crvmwinad02 
       auth:
         auth_url: "{{ lookup('env', 'OPENSTACK_AUTH_URL') }}"
         username: "{{ lookup('env', 'OPENSTACK_USERNAME') }}"
         password: "{{ lookup('env', 'OPENSTACK_PASSWORD') }}"
         project_name: "{{ lookup('env', 'OPENSTACK_PROJECT') }}"
         domain_name: "{{ lookup('env', 'OPENSTACK_DOMAIN') }}"                 
    register: floating_ip_info
    
  - name: Add VM to inventory
    add_host:
      #name: "{{ vm_ad01_created.server.hostname }}"
      #ansible_host: "{{ vm_ad01_created.server.addresses.shared[0].addr }}"      
      name: "{{ vm_ad01_created.server.hostname }}"
      ansible_host: "{{ floating_ip_info.floating_ip.floating_ip_address }}"      
      groups: cr_ad_grp
    when: vm_ad01_created is defined and vm_ad01_created.changed    


- name: CyberRange - AD01 - Play 1
  hosts: cr_ad_grp
  gather_facts: no
  collections:
    - openstack.cloud
  vars:
    ansible_user: "{{ lookup('env', 'VM_NODE_USER_02') }}"
    ansible_password: "{{ lookup('env', 'VM_NODE_PASSWORD') }}"
    ansible_connection: winrm
    ansible_shell_type: powershell
    ansible_ssh_port: 5986
    ansible_winrm_transport: ntlm     
    ansible_winrm_server_cert_validation: ignore
        
  tasks:
  - name: link NTP server to NZ
    win_command: 
      cmd: w32tm /config /manualpeerlist:".pool.ntp.org,0x8" /syncfromflags:manual /reliable:YES /update
    register: result
    ignore_errors: yes
    async: 600
    poll: 5

  - name: Sync Timezon to NTP
    win_command: 
      cmd: w32tm /resync
    register: result
    ignore_errors: yes
    async: 600
    poll: 5
          
  - name: Run command MDE Agent
    win_command: 
      cmd: C:\Users\Administrator\Documents\mdewin2022.cmd
    register: result
    ignore_errors: yes
    async: 600
    poll: 5
      
  - name: Del MDE Agent
    win_file: 
      path: C:\Users\Administrator\Documents\mdewin2022.cmd
      state: absent 

 
