---
- name: CyberRange
  hosts: localhost
  
  tasks:
  - name: Start Instance
    os_server:
       state: running
       name: crvmkaliusr06
       image: "kali2024img"
       key_name: os_key
       timeout: 200
       flavor: 3
       auto_ip: no
       network: 57325c59-2d2e-47f7-9d19-3d33771e2fee
       security_groups: default
       auth:
         auth_url: "{{ lookup('env', 'OPENSTACK_AUTH_URL') }}"
         username: "{{ lookup('env', 'OPENSTACK_USERNAME') }}"
         password: "{{ lookup('env', 'OPENSTACK_PASSWORD') }}"
         project_name: "{{ lookup('env', 'OPENSTACK_PROJECT') }}"
         domain_name: "{{ lookup('env', 'OPENSTACK_DOMAIN') }}"
       
       meta:
         os: windows


