---
- name: CyberRange
  hosts: localhost
  
  tasks:
  - name: Stop Instance
    os_server_action:
       action: stop
       name: crvmwinad01
       timeout: 200
       auth:
         auth_url: "{{ lookup('env', 'OPENSTACK_AUTH_URL') }}"
         username: "{{ lookup('env', 'OPENSTACK_USERNAME') }}"
         password: "{{ lookup('env', 'OPENSTACK_PASSWORD') }}"
         project_name: "{{ lookup('env', 'OPENSTACK_PROJECT') }}"
         domain_name: "{{ lookup('env', 'OPENSTACK_DOMAIN') }}"
    async: 600
    poll: 5
    register: vm_ad01_stopped

  - name: Debug inventory - vm_ad01_stopped
    debug:
      var: vm_ad01_stopped
      
  - name: Stop Instance
    os_server_action:
       action: stop
       name: crvmwindb20
       timeout: 200
       auth:
         auth_url: "{{ lookup('env', 'OPENSTACK_AUTH_URL') }}"
         username: "{{ lookup('env', 'OPENSTACK_USERNAME') }}"
         password: "{{ lookup('env', 'OPENSTACK_PASSWORD') }}"
         project_name: "{{ lookup('env', 'OPENSTACK_PROJECT') }}"
         domain_name: "{{ lookup('env', 'OPENSTACK_DOMAIN') }}"
    async: 600
    poll: 5
    register: crvmwindb20_stopped

  - name: Debug inventory - crvmwindb20_stopped
    debug:
      var: crvmwindb20_stopped
      
  - name: Stop Instance
    os_server_action:
       action: stop
       name: crvmwinap20
       timeout: 200
       auth:
         auth_url: "{{ lookup('env', 'OPENSTACK_AUTH_URL') }}"
         username: "{{ lookup('env', 'OPENSTACK_USERNAME') }}"
         password: "{{ lookup('env', 'OPENSTACK_PASSWORD') }}"
         project_name: "{{ lookup('env', 'OPENSTACK_PROJECT') }}"
         domain_name: "{{ lookup('env', 'OPENSTACK_DOMAIN') }}"
    async: 600
    poll: 5
    register: crvmwinap20_stopped

  - name: Debug inventory - crvmwinap20_stopped
    debug:
      var: crvmwinap20_stopped
      
  - name: Stop Instance
    os_server_action:
       action: stop
       name: crvmlin02
       timeout: 200
       auth:
         auth_url: "{{ lookup('env', 'OPENSTACK_AUTH_URL') }}"
         username: "{{ lookup('env', 'OPENSTACK_USERNAME') }}"
         password: "{{ lookup('env', 'OPENSTACK_PASSWORD') }}"
         project_name: "{{ lookup('env', 'OPENSTACK_PROJECT') }}"
         domain_name: "{{ lookup('env', 'OPENSTACK_DOMAIN') }}"
    async: 600
    poll: 5
    register: crvmlin02_stopped

  - name: Debug inventory - crvmlin02_stopped
    debug:
      var: crvmlin02_stopped  
      
                                    
