---
- name: CyberRange
  hosts: localhost
  
  tasks:      
  - name: Start Instance
    os_server_action:
       action: start
       name: crvmlin02
       timeout: 200
       auth:
         auth_url: "{{ lookup('env', 'OPENSTACK_AUTH_URL') }}"
         username: "{{ lookup('env', 'OPENSTACK_USERNAME') }}"
         password: "{{ lookup('env', 'OPENSTACK_PASSWORD') }}"
         project_name: "{{ lookup('env', 'OPENSTACK_PROJECT') }}"
         domain_name: "{{ lookup('env', 'OPENSTACK_DOMAIN') }}"
    async: 600
    poll: 5
    register: crvmlin02_started

  - name: Debug inventory - crvmlin02_started
    debug:
      var: crvmlin02_started      
      
                                    
