--- 
- name: CyberRange
  hosts: localhost  
  
  tasks:  
  - name: Create VM Linux App 
    os_server:
       state: present
       name: crvmlin02
       image: "ubuntu2204img"
       key_name: os_key
       timeout: 200
       flavor: 3
       auto_ip: no
       network: 57325c59-2d2e-47f7-9d19-3d33771e2fee
       security_groups: default
       auth:
         auth_url: "{{ lookup('env', 'OPENSTACK_AUTH_URL') }}"
         username: "{{ lookup('env', 'OPENSTACK_USERNAME') }}"
         password: "{{ lookup('env', 'OPENSTACK_PASSWORD') }}"
         project_name: "{{ lookup('env', 'OPENSTACK_PROJECT') }}"
         domain_name: "{{ lookup('env', 'OPENSTACK_DOMAIN') }}"    
       meta:
         os: linux        
    async: 600
    poll: 5
    register: vm_lnx_created

  - name: Debug vm_lnx_created variable
    debug:
       var: vm_lnx_created

  - name: Create floating ip - Linx
    os_floating_ip:
       state: present
       network: public
       server: crvmlin02 
       auth:
         auth_url: "{{ lookup('env', 'OPENSTACK_AUTH_URL') }}"
         username: "{{ lookup('env', 'OPENSTACK_USERNAME') }}"
         password: "{{ lookup('env', 'OPENSTACK_PASSWORD') }}"
         project_name: "{{ lookup('env', 'OPENSTACK_PROJECT') }}"
         domain_name: "{{ lookup('env', 'OPENSTACK_DOMAIN') }}"                 
    register: floating_ip_info

  - name: Set fact for floating IPs
    set_fact:
       floating_ips: "{{ floating_ip_info.floating_ip.floating_ip_address }}"

  - name: Output floating ip
    debug:
       var: floating_ips
       
  - name: Add VM to inventory
    add_host:
      name: "{{ vm_lnx_created.server.id }}"
      ansible_host: "{{ floating_ip_info.floating_ip.floating_ip_address }}"
      groups: cr_server_lnx_grp
    when: vm_lnx_created is defined and vm_lnx_created.changed

  - name: Debug inventory
    debug:
      var: hostvars

- name: CyberRange - Linux - Play 4
  hosts: cr_server_lnx_grp
  vars:
    ansible_user: root

  tasks:
  - name: Debug inventory - server 
    debug:
      var: cr_server_lnx_grp
      
  - name: Run command on OpenStack VM
    shell: "echo $(date) | md5sum | awk '{print substr($1,length($1)-31)}' > /home/ubuntu/flag.txt"
 
  - name: Run command on OpenStack VM
    shell: "echo $(date) | md5sum | awk '{print substr($1,length($1)-31)}' > /root/root.txt"
    
  - name: Run command on OpenStack VM
    shell: "mkdir /tmp/uploads && chown ubuntu:ubuntu /tmp/uploads"
     
  - name: Run command on OpenStack VM
    shell: "echo {{ lookup('env', 'WIN_USER_01_TOKEN') }} > /root/user_token.txt"
         
  - name: Run command on OpenStack VM
    shell: "[ ! -d '/tmp/uploads' ] && mkdir -p '/tmp/uploads' || echo 'Failed to create directory'"
